apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: txmrx1kuz-nodejs 
  janus-idp.io/tekton: txmrx1kuz-nodejs
  backstage.io/kubernetes-id: txmrx1kuz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: txmrx1kuz-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  